package main;
// Generated Sep 1, 2019 9:18:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LevelOfEquipment generated by hbm2java
 */
public class LevelOfEquipment  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Car> cars = new HashSet<Car>(0);

    public LevelOfEquipment() {
    }

    public LevelOfEquipment(String name, Set<Car> cars) {
       this.name = name;
       this.cars = cars;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


