package main;
// Generated Sep 1, 2019 9:18:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private Integer id;
     private Brand brand;
     private EngineType engineType;
     private String name;
     private String year;
     private float price;
     private String image;
     private Set<Car> cars = new HashSet<Car>(0);

    public Model() {
    }

	
    public Model(Brand brand, EngineType engineType, float price, String image) {
        this.brand = brand;
        this.engineType = engineType;
        this.price = price;
        this.image = image;
    }
    public Model(Brand brand, EngineType engineType, String name, String year, float price, String image, Set<Car> cars) {
       this.brand = brand;
       this.engineType = engineType;
       this.name = name;
       this.year = year;
       this.price = price;
       this.image = image;
       this.cars = cars;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public EngineType getEngineType() {
        return this.engineType;
    }
    
    public void setEngineType(EngineType engineType) {
        this.engineType = engineType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }


}


