package main;
// Generated Sep 1, 2019 9:18:07 PM by Hibernate Tools 4.3.1



/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer id;
     private Car car;
     private User user;
     private Float price;

    public Order() {
    }

	
    public Order(Car car, User user) {
        this.car = car;
        this.user = user;
    }
    public Order(Car car, User user, Float price) {
       this.car = car;
       this.user = user;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }




}


